static struct os_fingerprint tcp_fps[] = {
    { "2_64_65535_8bf9e292397e",    os_hint_freebsd     },
    { "2_64_64800_83b2f9a5576c",    os_hint_linux       },
    { "2_64_64240_2e3cee914fc1",    os_hint_linux       },
    { "2_64_29200_2e3cee914fc1",    os_hint_linux       },
    { "2_64_29200_d853e95bd80f",    os_hint_linux       }, /* Sonos */
    { "2_64_14600_8c07a80cc645",    os_hint_linux       }, /* QNAP */
    { "2_64_65535_d876f498b09e",    os_hint_android     },
    { "2_64_65535_685ad951a756",    os_hint_android     },
    { "2_64_65535_41a9d5af7dd3",    os_hint_android     },
    { "2_128_64240_6bb88f5575fd",   os_hint_windows     },
    { "2_128_8192_4697958db063",    os_hint_windows     }, /* Windows 7 */
    { "194_64_65535_15db81ff8b0d",  os_hint_ios_ipad_os },
    { "2_64_65535_41a9d5af7dd3",    os_hint_ios_ipad_os },
    { "194_64_65535_dd5737e4fedb",  os_hint_ios_ipad_os },
    { "194_64_65535_d29295416479",  os_hint_macos       },
    { "2_64_65535_d29295416479",    os_hint_macos       },
    { "2_64_65535_dd5737e4fedb",    os_hint_macos       },
    { NULL,                         os_hint_unknown     },
  };

