-t -I
-q -e 0
-L ./lists/public_suffix_list.dat
--cfg=dpi.compute_entropy,0
--cfg=dpi.guess_on_giveup,0x02
--cfg=flow_risk_lists.load,0
--cfg=flow_risk.all.info,0
--cfg=flow.use_client_ip_in_guess,0
--cfg=openvpn,dpi.heuristics,0x01
--cfg=stun,max_packets_extra_dissection,4
--cfg=tcp_ack_payload_heuristic,0
--cfg=metadata.ndpi_server_fingerprint,0
