name: FreeBSD Build
on:
  workflow_dispatch:
  schedule:
    #At the end of every day
    - cron: '0 0 * * *'

jobs:
  test:
    name: FreeBSD
    runs-on: ubuntu-latest
    env:
      CFLAGS: -Werror -DNDPI_EXTENDED_SANITY_CHECKS -g -O2
    steps:
    - uses: actions/checkout@v6
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@d1e65811565151536c0c894fff74f06351ed26e6 #v1.4.5
      with:
        envs: 'CFLAGS'
        usesh: true
        copyback: false
        release: "15.0"
        prepare: |
          pkg install -y gcc git gettext flex bison libtool autoconf automake devel/pkgconf gmake libpcap json-c
        run: |
          echo "Working Directory: $(pwd)"
          echo "User.............: $(whoami)"
          echo "FreeBSD Version..: $(freebsd-version)"
          ./autogen.sh && ./configure
          gmake -j $(nproc) all
          gmake -j $(nproc) -C example
          ./example/ndpiReader -H
          #Avoid running tests to be fast: we are only interested in basic compilation
