name: Cross-compilation
on:
  release:
    types: [created]
  workflow_dispatch:
  schedule:
    #At the end of every day
    - cron: '0 0 * * *'

jobs:
  crosscompilation-aarch64:
    name: AArch64 on ubuntu-latest x86_64
    runs-on: ubuntu-latest
    env:
      CFLAGS: -Werror -DNDPI_EXTENDED_SANITY_CHECKS
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run script
        run: |
          ./utils/cross-compile-test.sh --full #No real tests

  crosscompilation-s390x:
    name: s390x on ubuntu-latest x86_64
    runs-on: ubuntu-latest
    env:
      CFLAGS: -Werror -DNDPI_EXTENDED_SANITY_CHECKS
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run script
        run: |
          ./utils/cross-compile-test-s390x.sh --full #No real tests
