name: RPM Build
on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build / RPM (Alma Linux)
    runs-on: ubuntu-latest
    container:
      image: almalinux:8
    steps:
    - uses: actions/checkout@v6

    - name: Install Alma Linux Prerequisites
      run: |
        dnf -y --enablerepo=powertools install libpcap-devel
        yum install -y autoconf automake make rpm-build libtool pkg-config gettext json-c-devel flex bison

    - name: Configure nDPI
      run: |
        # symlink source directory for ndpi.spec
        ln -sr . $HOME/nDPI
        ./autogen.sh && ./configure
        cd packages/rpm
        ./configure

    - name: Build RPM package
      run: |
        make -C packages/rpm package

    - name: Test RPM package
      run: |
        yum install -y ${HOME}/rpmbuild/RPMS/x86_64/*.rpm
        ndpiReader -i ./tests/pcap/quic-v2.pcapng
        test -d /usr/include/ndpi
