name: Build
on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
    types: [opened, synchronize, reopened]
  release:
    types: [created]
jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.gcrypt }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "ubuntu-18.04", "macOS-latest", "macos-11"]
        gcrypt: ["--disable-gcrypt", ""]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - name: Install Ubuntu Prerequisites
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool pkg-config gettext libjson-c-dev flex bison libpcap-dev
        sudo apt-get install gcc-arm-linux-gnueabihf gcc-mingw-w64 libc6-dev
    - name: Install Ubuntu Prerequisites (libgcrypt)
      if: startsWith(matrix.os, 'ubuntu') && !startsWith(matrix.gcrypt, '--disable-gcrypt')
      run: |
        sudo apt-get install libgcrypt20-dev
    - name: Installing MacOS prerequisites
      if: startsWith(matrix.os, 'macOS')
      run: |
        brew install autoconf automake libtool pkg-config gettext json-c
    - name: Install MacOS Prerequisites (libgcrypt)
      if: startsWith(matrix.os, 'macOS') && !startsWith(matrix.gcrypt, '--disable-gcrypt')
      run: |
        brew install libgcrypt
    - name: Build nDPI
      run: |
        env CFLAGS='-Werror' ./autogen.sh --enable-debug-messages ${{ matrix.gcrypt }}
        make all
    - name: Test nDPI
      run: |
        cd tests
        ./do.sh
        ./do-unit.sh
        ./do-dga.sh
        cd ..
    - name: Build nDPI [ARM] (runs only on ubuntu jobs)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        make distclean && env CFLAGS='-Werror' ./autogen.sh --host=arm-linux-gnueabihf --with-only-libndpi ${{ matrix.gcrypt }}
        make all
    - name: Build nDPI [Mingw-w64] (runs only on ubuntu jobs)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        make distclean && ./autogen.sh --host=x86_64-w64-mingw32 ${{ matrix.gcrypt }}
        make all
